#!/usr/bin/env bash

set -euxo pipefail

HDF5_ROOT=/users/ankushj/repos/hdf5/hdf5-2004-psm/CMake-hdf5-1.10.7
TAU_ROOT=/users/ankushj/repos/amr-workspace/tau-psm-2004/tau-2.31
MPI_HOME=/users/ankushj/amr-workspace/install
PHOEBUS_HOME=/users/ankushj/repos/phoebus
PHOEBUS_BUILDDIR=build-psm-wtaucc

HDF5_PATH=$HDF5_ROOT/HDF5-1.10.7-Linux/HDF_Group/HDF5/1.10.7/share/cmake/hdf5
TAU_CC="$TAU_ROOT/x86_64/bin/tau_cc.sh"
TAU_CXX="$TAU_ROOT/x86_64/bin/tau_cxx.sh"
TAU_CXX_COMPILE_OPTS="-optCompInst"

PHOEBUS_BUILDPATH=$PHOEBUS_HOME/$PHOEBUS_BUILDDIR

export MPI_HOME=$MPI_HOME
export TAU_MAKEFILE=$TAU_ROOT/include/Makefile

CMAKEOPTS=""
CMAKEOPTS="$CMAKEOPTS -DHDF5_DIR=$HDF5_PATH"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_C_COMPILER=$TAU_CC"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_C_COMPILE_OPTIONS=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_C_FLAGS=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_C_FLAGS_INIT=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_CXX_COMPILER=$TAU_CXX"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_CXX_FLAGS=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DCMAKE_CXX_FLAGS_INIT=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DMPI_CXX_COMPILER=$TAU_CXX"
CMAKEOPTS="$CMAKEOPTS -DMPI_CXX_COMPILE_OPTIONS=$TAU_CXX_COMPILE_OPTS"
CMAKEOPTS="$CMAKEOPTS -DMPI_CXX_LIB_NAMES=mpicxx;mpi"
CMAKEOPTS="$CMAKEOPTS -DMPI_CXX_HEADER_DIR=$MPI_HOME/include"
CMAKEOPTS="$CMAKEOPTS -DMPI_mpi_LIBRARY=$MPI_HOME/lib/libmpi.so"
CMAKEOPTS="$CMAKEOPTS -DMPI_mpicxx_LIBRARY=$MPI_HOME/lib/libmpicxx.so"

rm -rf $PHOEBUS_BUILDPATH/*
cd $PHOEBUS_BUILDPATH
# export $ENVOPTS
cmake $CMAKEOPTS ..
